services:
  php:
    build:
      context: php-dockerfile\
      dockerfile: Dockerfile
    container_name: php_app
    ports:
      - "5000:80"
    volumes:
      - ./app-php:/var/www/html
    depends_on:
       mysql:
          condition: service_healthy
    networks:
      - my-network



  mysql:
    build:
      context: mysql-dockerfile\
      dockerfile: Dockerfile
    container_name: db-mysql
    environment:
      MYSQL_ROOT_PASSWORD: redhat123
      MYSQL_DATABASE: usuarios
      MYSQL_USER: charlie
      MYSQL_PASSWORD: redhat
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my-network
    healthcheck:
      test:  ["CMD", "test -f var/lib/mysql/usuarios"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  my-network:    
    driver: bridge  
    ipam:
      config:
        - subnet: 192.168.0.0/24 
          gateway: 192.168.0.1

volumes:
  mysql_data: