FROM mysql:latest

# Set environment variables (change as needed)
ENV MYSQL_ROOT_PASSWORD=redhat123
ENV MYSQL_DATABASE=usuarios
ENV MYSQL_USER=charlie
ENV MYSQL_PASSWORD=redhat

# Expose MySQL port
EXPOSE 3306